# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "example-sno"
  namespace: "example-sno"
spec:
  baseDomain: "ocpran.com"
  pullSecretRef:
    name: "pull-secret"
  clusterImageSetNameRef: "img4.17.7-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnGdbHlyK3+7K/2gdWTaov6hMz/wHlCy0gnad/r0lAb0ziFloZ8jG3VyTFpB7COnOULjq8nCznLjE1tKvgSRlFh/hvi+HNXE2C7q/MkIWzzAxRcPOLVJz9P6f0HvOA3rekVt81eOf/NAoRqoJ1qUod8pDDd7zWGIINOCDSROGTQzHYD77EJ0g7JX1ctzT1Rnn4BmPPoffNyqFAy0LlhLTRcZ3FSwm1gMH18d1QniBHYPYRfNM2L//cRzgqwdrXVjLVTtgOoNyzta+IQzLod0Zbr0IEPvZyyljAuSlupmcocj6bSNDe95ThuKpY0pYBH3l/cOoe3N300j+ETGhmTVs7Xq6sWIJrt/BRyl7Lkg3dyt0s9t5wNm5pNitHXHjmGC53m8NLTev0ceGzxLnoe4+8/Aes9keX92lELAEqZorNKVwtFvnKhIFD3tGzfQN5o9qb8QoxqNTmGNTffEXpNPK6fvME3HT6/JXOcgyiTUGrHoBLlOLfw2vMARAOzK8kLnc= root@bastion500.ocpran.com"
  clusters:
  - clusterName: "example-sno"
    networkType: "OVNKubernetes"
    # installConfigOverrides is a generic way of passing install-config
    # parameters through the siteConfig.  The 'capabilities' field configures
    # the composable openshift feature.  In this 'capabilities' setting, we
    # remove all the optional set of components.
    # Notes:
    # - OperatorLifecycleManager is needed for 4.15 and later
    # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
    # - Ingress is needed for 4.16 and later
    installConfigOverrides: |
      {
        "capabilities": {
          "baselineCapabilitySet": "None",
          "additionalEnabledCapabilities": [
            "NodeTuning",
            "OperatorLifecycleManager",
            "Ingress"
          ]
        }
      }
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.sno-extra-manifest.
    # extraManifestPath: sno-extra-manifest
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
      #      du-profile: "latest"
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      #      common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
      #      group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      #sites : "example-sno"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.0.0/24
    serviceNetwork:
      - 172.30.0.0/16
  #  additionalNTPSources:
   #   - 1111:2222:3333:4444::2
    # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
    # please see Workload Partitioning Feature for a complete guide.
    # cpuPartitioningMode: AllNodes
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "example-node1.ocpran.com"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia+https://192.168.0.15/redfish/v1/Systems/1/"
        bmcCredentialsName:
          name: "bmc-secret"
        bootMACAddress: "ec:eb:b8:9c:f4:b0"
        # Use UEFISecureBoot to enable secure boot, UEFI to disable.
        bootMode: "UEFISecureBoot"
      #  rootDeviceHints:
       #   deviceName: "/dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0"
        # disk partition at `/var/lib/containers` with ignitionConfigOverride. Some values must be updated. See DiskPartitionContainer.md for more details
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "ec:eb:b8:9c:f4:b0"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                ipv6:
                  enabled: false
                  address:
                  # For SNO sites with static IP addresses, the node-specific,
                  # API and Ingress IPs should all be the same and configured on
                  # the interface
                  - ip: 192.168.0.140
                    prefix-length: 24
            dns-resolver:
              config:
                search:
                - ocpran.com
                server:
                - 192.168.0.149
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: eno1
                next-hop-address: 192.168.0.1
                table-id: 254
